The precedent commit  :  https://github.com/openpsa/grid.js/commit/eaee8e668b4d67c33055050c534fcc2682521cd7#diff-2d010088e9cda4a876dbc3e2399c83a0
introduce, when, in case of controlling grid by another grid (for example by an action in onSelectRow), the following bug :

ReferenceError: grid is not defined
$(grid.cDiv).nextAll("div").removeClass('ui-corner-top');

This commit fix it.